import type { AttributeKey, Evolution, KaguneEffect, KaguneFamily, Perk } from "./data";

export const combatManeuvers = [
  { name: "Investida", description: "Antes de um ataque corpo a corpo, percorra ao menos metade do Deslocamento: +1 Passo de Dano, mas -2 dados na primeira defesa antes do próximo turno. Não combina com outra Investida." },
  { name: "Ataque de Ruptura", description: "Antes de atacar, sofra -2 dados de dano. Se ainda causar dano após a RD, reduza a RD do alvo em 2 contra o próximo ataque até o início do turno dele. Não acumula." },
  { name: "Derrubar", description: "Ataque corpo a corpo com -2 dados de acerto. Ao acertar, cause dano ou derrube. Alvo caído perde a Reação até se levantar e gasta parte do movimento." },
  { name: "Desarmar", description: "Ataque a arma ou objeto com -2 dados de acerto. Ao superar a defesa, não cause dano e force o alvo a largá-lo. Não funciona em armas integradas ou impossíveis de soltar." },
  { name: "Proteger", description: "Como Reação, mova até 1 espaço e torne-se o alvo de um ataque contra aliado adjacente, se fisicamente possível. Não concede uma segunda defesa contra o mesmo ataque." },
  { name: "Preparar Ação", description: "Gaste a Ação e defina um gatilho perceptível. Se ocorrer antes do próximo turno, execute imediatamente a ação preparada; caso contrário, ela é perdida." },
  { name: "Finta", description: "Sacrifique 2 dados de dano antes de um ataque corpo a corpo. Se o alvo usar Bloqueio ou Esquiva, ele sofre -1 dado nessa defesa. Não multiplica por ataques adicionais." },
  { name: "Ataque de Cobertura", description: "Em ataque à distância, sacrifique o dano. Ao acertar, o alvo interrompe a movimentação ou continua e sofre -2 dados na próxima defesa." },
  { name: "Pressionar", description: "Ao acertar o mesmo alvo por dois turnos seguidos, ganhe +1 dado para impedir sua fuga ou reposicionamento até errar ou trocar de alvo." },
  { name: "Recuperar Guarda", description: "Gaste a Ação sem atacar. Até o começo do próximo turno, receba +2 dados na primeira defesa." },
] as const;

export const expansionKaguneEffects: KaguneEffect[] = [
  { id: "gancho-predatorio", name: "Gancho Predatório", family: "Geral", cost: 3, maxRank: 1, type: "Ativo · 2 RC", description: "Ao acertar em alcance da Kagune, puxe o alvo 1 espaço em vez de empurrá-lo. Alvos muito maiores podem exigir teste do Atributo Principal." },
  { id: "ancoragem", name: "Ancoragem", family: "Geral", cost: 3, maxRank: 1, type: "Ativo · Biológico", description: "Fixe a Kagune em uma superfície: +2 dados contra empurrões, arremessos e quedas, além de usos narrativos de escalada e sustentação." },
  { id: "finta-organica", name: "Finta Orgânica", family: "Geral", cost: 5, maxRank: 1, type: "Passivo", description: "Uma vez por turno, ao errar com a Kagune, ganhe +1 dado de acerto contra o mesmo alvo, até +2. O bônus acaba ao acertar ou trocar de alvo." },
  { id: "recuo-vivo", name: "Recuo Vivo", family: "Geral", cost: 5, maxRank: 1, type: "Passivo", description: "Uma vez por turno, após atacar à distância com a Kagune, mova 1 espaço. Esse movimento não ativa outro Recuo Vivo." },
  { id: "absorcao-impacto", name: "Absorção de Impacto", family: "Geral", cost: 6, maxRank: 1, type: "Ativo · 3 RC", description: "Uma vez por rodada, após aplicar RD, reduza o dano restante em metade do Grau." },
  { id: "reflexo-kakuhou", name: "Reflexo da Kakuhou", family: "Geral", cost: 5, maxRank: 1, type: "Passivo", description: "A primeira defesa no turno em que a Kagune é ativada recebe +2 dados." },
  { id: "estouro-rc", name: "Estouro de RC", family: "Geral", cost: 6, maxRank: 1, type: "Ativo · 5 RC", description: "Antes de atacar, ganhe +3 dados de dano; até o próximo turno, seus outros ataques de Kagune sofrem -1 dado de dano." },
  { id: "reserva-caca", name: "Reserva de Caça", family: "Geral", cost: 8, maxRank: 1, type: "Passivo", description: "Ao derrotar pessoalmente uma ameaça real com Kagune, reduza em 1 RC a próxima habilidade ativa até o fim do próximo turno, mínimo 1 RC." },
  { id: "nervos-rc", name: "Nervos de RC", family: "Geral", cost: 5, maxRank: 1, type: "Passivo · Biológico", description: "Perceba presença e direção aproximada de Kagunes ativas em alcance Próximo, mesmo sem vê-las; não revela identidade ou posição exata." },
  { id: "predacao-instintiva", name: "Predação Instintiva", family: "Geral", cost: 6, maxRank: 1, type: "Passivo", description: "Contra inimigo em alcance da Kagune com metade ou menos da Vida, o primeiro ataque do turno recebe +1 dado de acerto." },
  { id: "kagune-reativa", name: "Kagune Reativa", family: "Geral", cost: 8, maxRank: 1, type: "Passivo", description: "Ao sofrer dano após RD, ganhe +1 dado de dano no próximo ataque contra o responsável, até +3. Os acúmulos somem ao atingi-lo." },
  { id: "mudanca-relampago", name: "Mudança Relâmpago", family: "Geral", cost: 6, maxRank: 1, type: "Mudança de Forma · +3 RC", requirement: "Mudança de Forma", description: "Uma vez por turno, realize sem Ação uma Mudança de Forma que normalmente exigiria Ação. Não concede ataques adicionais." },
];

const quimera = (
  id: string,
  name: string,
  cost: number,
  types: KaguneFamily[],
  description: string,
  minGrade = 0,
  options: Partial<Perk> = {},
): Perk => ({
  id, name, cost, category: "Kagune Quimera", description,
  requirement: `${types.join(" + ")}${minGrade ? `; Grau ${minGrade}+` : ""}`,
  kaguneTypes: types, minGrade: minGrade || undefined, ...options,
});

const requirementLabels: Record<AttributeKey, string> = {
  forca: "Força", vigor: "Vigor", precisao: "Precisão", agilidade: "Agilidade",
  raciocinio: "Raciocínio", percepcao: "Percepção", presenca: "Presença", controle: "Controle",
};

const hybrid = (id: string, name: string, cost: number, requirements: Partial<Record<AttributeKey, number>>, description: string): Perk => ({
  id, name, cost, category: "Híbrida", description, requirements,
  requirement: Object.entries(requirements).map(([key, value]) => `${requirementLabels[key as AttributeKey]} ${value}`).join("; "),
});

const combat = (id: string, name: string, cost: number, description: string, minGrade = 0): Perk => ({
  id, name, cost, category: "Combate", description, minGrade: minGrade || undefined,
  requirement: minGrade ? `Grau ${minGrade}+` : "Universal",
});

export const expansionPerks: Perk[] = [
  quimera("asa-escudada", "Asa Escudada", 5, ["Ukaku", "Koukaku"], "Uma vez por rodada, contra ataque à distância, oriente placas Koukaku entre as asas e receba +2 RD."),
  quimera("canhao-ombro", "Canhão de Ombro", 6, ["Ukaku", "Koukaku"], "Se não se mover antes de disparar, o primeiro ataque à distância do turno recebe +2 dados de acerto."),
  quimera("cristais-tungstenio", "Cristais de Tungstênio", 8, ["Ukaku", "Koukaku"], "Por 4 RC antes de um disparo, receba +2 Passos de Dano e -2 dados de dano.", 6),
  quimera("plataforma-tiro", "Plataforma de Tiro", 8, ["Ukaku", "Koukaku"], "Cada turno inteiro parado concede +1 dado de acerto à distância, até +3; mover-se remove os acúmulos.", 6),
  quimera("muralha-penas", "Muralha de Penas", 10, ["Ukaku", "Koukaku"], "Como Reação por 5 RC, ganhe RD igual à metade da Precisão base contra um ataque; se anular tudo, mova 1 espaço.", 8),
  quimera("railgun-rc", "Railgun de RC", 15, ["Ukaku", "Koukaku"], "Gaste uma Ação e 8 RC: o próximo disparo recebe +4 dados de acerto, +6 dados de dano e +1 Passo. Não combina com condensação.", 8),
  quimera("bombardeiro-couracado", "Bombardeiro Couraçado", 20, ["Ukaku", "Koukaku"], "Voando, mantenha a couraça para +3 RD. Uma vez por turno, após sofrer ataque sem dano, desloque-se 1 espaço no ar.", 10),
  quimera("ultimo-horizonte", "Último Horizonte", 30, ["Ukaku", "Koukaku"], "Uma vez por sessão, sacrifique a RD Koukaku e 20 RC: +10 dados de dano, +4 acerto, +2 Passos e ignore metade da RD; depois, RD Koukaku -6 por 3 turnos.", 12),

  quimera("tentaculos-pena", "Tentáculos de Pena", 5, ["Ukaku", "Rinkaku"], "Por 2 RC, ataques de Rinkaku com extremidades cristalizadas alcançam 1 grau além do normal."),
  quimera("sangue-asas", "Sangue em Forma de Asas", 6, ["Ukaku", "Rinkaku"], "Ao recuperar Vida por regeneração biológica, o próximo ataque Ukaku recebe +1 dado de dano por 5 Vida recuperados, até +3."),
  quimera("hidra-cristalina", "Hidra Cristalina", 8, ["Ukaku", "Rinkaku"], "Após ataque corpo a corpo de Rinkaku acertar, gaste 3 RC para somar +3 dados de dano Ukaku ao mesmo ataque, uma vez por turno.", 0, { requiredEffect: "multiplas-caudas", requirement: "Ukaku + Rinkaku; Múltiplas Caudas" }),
  quimera("fragmentacao-regenerativa", "Fragmentação Regenerativa", 8, ["Ukaku", "Rinkaku"], "Quando uma cauda é destruída, ela explode; em falha de defesa, o responsável sofre metade dos dados básicos da Kagune. Uma vez por turno.", 6),
  quimera("muda-penas", "Muda de Penas", 10, ["Ukaku", "Rinkaku"], "Após Esquiva bem-sucedida, gaste 4 RC para mover 1 espaço adicional; o próximo ataque recebe +2 dados de dano.", 8),
  quimera("regeneracao-explosiva", "Regeneração Explosiva", 15, ["Ukaku", "Rinkaku"], "Ao regenerar cauda, gaste +5 RC para ela atacar imediatamente com -2 dados de acerto, uma vez por turno.", 8),
  quimera("tempestade-carne", "Tempestade de Carne", 20, ["Ukaku", "Rinkaku"], "Por 12 RC e 2 turnos, perder cauda, sofrer dano ou regenerar Vida gera carga; cada carga dá +1 dado de dano Ukaku e Rinkaku, até 5.", 10),
  quimera("fenix-centopeia", "Fênix Centopeia", 30, ["Ukaku", "Rinkaku"], "Uma vez por sessão, ao cair a 0 Vida, gaste 25 RC: fique com 1, regenere caudas e no próximo turno ganhe +4 dano, +2 acerto e uma habilidade ativa gratuita; depois desative a Kagune e perca 10 RC.", 12),

  quimera("cauda-estabilizadora", "Cauda Estabilizadora", 5, ["Ukaku", "Bikaku"], "Após se mover, ignore o primeiro dado de penalidade em um ataque à distância no turno."),
  quimera("leme-caca", "Leme de Caça", 5, ["Ukaku", "Bikaku"], "No ar ou em movimento rápido, receba +1 dado em Esquiva."),
  quimera("disparo-oportunidade", "Disparo de Oportunidade", 8, ["Ukaku", "Bikaku"], "Use a Reação para disparar com Ukaku quando inimigo abandonar seu alcance corpo a corpo sem proteção.", 6),
  quimera("cauda-ricochete", "Cauda Ricochete", 8, ["Ukaku", "Bikaku"], "Reduza em 2 dados as penalidades por cobertura em disparos Ukaku.", 6),
  quimera("predador-angulo-morto", "Predador de Ângulo Morto", 12, ["Ukaku", "Bikaku"], "Ao atacar de direção diferente do ataque anterior, ganhe +2 dados de acerto e +2 dados de dano.", 8),
  quimera("mergulho-escarlate", "Mergulho Escarlate", 15, ["Ukaku", "Bikaku"], "Após mover 2 espaços em linha, gaste 6 RC: ataque corpo a corpo com +3 dados de dano e +1 Passo; depois mova 1 espaço.", 8),
  quimera("rei-ceu", "Rei do Céu", 20, ["Ukaku", "Bikaku"], "Enquanto não ficar parado por um turno inteiro, +2 dados de Esquiva; após Esquiva, o próximo disparo recebe +2 acerto.", 10),
  quimera("linha-execucao", "Linha de Execução", 30, ["Ukaku", "Bikaku"], "Uma vez por sessão, por 3 turnos, mudar posição antes de atacar gera Vetor (+1 acerto e dano), até 5; consuma 5 para ignorar metade da RD e ganhar +2 Passos.", 12),

  quimera("placas-regenerativas", "Placas Regenerativas", 5, ["Koukaku", "Rinkaku"], "No começo do turno, recupere 1 RD Koukaku perdida temporariamente; não recupera RD sacrificada por finalizadores."),
  quimera("tentaculo-blindado", "Tentáculo Blindado", 6, ["Koukaku", "Rinkaku"], "Uma cauda por turno recebe +2 dados de dano, mas não pode ser usada para defesa até o próximo turno."),
  quimera("escudo-vivo", "Escudo Vivo", 8, ["Koukaku", "Rinkaku"], "Reserve uma cauda sem atacar para receber +2 RD até o começo do próximo turno.", 6),
  quimera("casco-cresce", "Casco que Cresce", 8, ["Koukaku", "Rinkaku"], "Ao sofrer dano após RD, ganhe Casco, até 3; cada um fornece +1 RD. Um turno inteiro sem dano remove todos.", 6),
  quimera("espinhos-retaliacao", "Espinhos de Retaliação", 12, ["Koukaku", "Rinkaku"], "Ao bloquear completamente golpe corpo a corpo, uma cauda ataca com metade dos dados, uma vez por turno, sem gerar ataques.", 8),
  quimera("carne-mineral", "Carne Mineral", 15, ["Koukaku", "Rinkaku"], "Por 8 RC e 3 turnos: +3 RD, regeneração recebida +25% e -1 dado de Esquiva. Não multiplica cura total ou membros.", 8),
  quimera("fortaleza-ambulante", "Fortaleza Ambulante", 20, ["Koukaku", "Rinkaku"], "Mover 1 espaço não remove bônus como Montanha Inamovível; caudas reservadas para defesa fornecem +1 RD adicional.", 10),
  quimera("leviata-imortal", "Leviatã Imortal", 30, ["Koukaku", "Rinkaku"], "Uma vez por sessão, gaste 20 RC: por 3 turnos +5 RD, +3 dano, regenere a primeira cauda destruída por turno e ignore empurrões; depois RD de Kagune -6 por 2 turnos.", 12),

  quimera("guarda-escorpiao", "Guarda de Escorpião", 5, ["Koukaku", "Bikaku"], "Uma vez por rodada, após Bloquear, ganhe +1 dado de acerto no próximo ataque Bikaku contra o agressor."),
  quimera("arma-contrapeso", "Arma de Contrapeso", 6, ["Koukaku", "Bikaku"], "Ao usar arma Koukaku corpo a corpo, a Bikaku funciona como contrapeso e concede +1 dado de acerto."),
  quimera("postura-dupla", "Postura Dupla", 8, ["Koukaku", "Bikaku"], "No início do turno, escolha Guarda (+2 RD) ou Duelo (+2 dados de dano); trocar não gasta Ação.", 6),
  quimera("lanca-escorpionica", "Lança Escorpiônica", 8, ["Koukaku", "Bikaku"], "Aumente em 1 o alcance corpo a corpo da arma Koukaku; ataques de oportunidade com ela ganham +2 dados de dano.", 6),
  quimera("defesa-perfurante", "Defesa Perfurante", 12, ["Koukaku", "Bikaku"], "Após bloquear ataque corpo a corpo e sofrer 0 dano, gaste 4 RC: o próximo ataque contra o inimigo ignora 2 RD.", 8),
  quimera("duelo-absoluto", "Duelo Absoluto", 15, ["Koukaku", "Bikaku"], "Escolha inimigo por rodada: +1 acerto e defesa contra ele, mas -1 defesa contra os demais.", 8),
  quimera("arsenal-carrasco", "Arsenal do Carrasco", 20, ["Koukaku", "Bikaku"], "Escolha por turno: Sabre +3 acerto, Machado +4 dano, Alabarda +2 acerto e alcance ou Escudo-Cauda +3 RD.", 10),
  quimera("cavaleiro-escarlate", "Cavaleiro Escarlate", 30, ["Koukaku", "Bikaku"], "Uma vez por sessão, por 3 turnos: +4 RD, +2 acerto, oportunidades +5 dano e a primeira defesa corpo a corpo completa permite ataque adicional com metade dos dados.", 12),

  quimera("cauda-alfa", "Cauda Alfa", 5, ["Rinkaku", "Bikaku"], "Escolha uma cauda Alfa por cena: +1 dado de acerto. Se destruída, escolha outra no próximo turno."),
  quimera("laco-predatorio", "Laço Predatório", 6, ["Rinkaku", "Bikaku"], "+2 dados para agarrar ou impedir movimento usando caudas."),
  quimera("danca-serpentes", "Dança das Serpentes", 8, ["Rinkaku", "Bikaku"], "Quando duas caudas diferentes acertarem o mesmo alvo, o próximo ataque de cauda recebe +2 dados de dano, uma vez por turno.", 6),
  quimera("guarda-hidra", "Guarda de Hidra", 8, ["Rinkaku", "Bikaku"], "Reserve uma cauda para obter +2 RD ou +2 dados de Esquiva contra um ataque.", 6),
  quimera("constricao", "Constrição", 12, ["Rinkaku", "Bikaku"], "Após acertar com cauda, gaste 4 RC para prender: alvo -2 dados para deslocamento e a cauda fica ocupada.", 8),
  quimera("predador-reacao", "Predador de Reação", 15, ["Rinkaku", "Bikaku"], "Quando inimigo errar ataque corpo a corpo, marque-o; o próximo ataque contra ele recebe +2 acerto e +3 dano.", 8),
  quimera("cem-serpentes", "Cem Serpentes", 20, ["Rinkaku", "Bikaku"], "Ao atacar inimigos diferentes no mesmo turno, ganhe +1 dado de dano por alvo anterior, até +4.", 10),
  quimera("orochi", "Orochi", 30, ["Rinkaku", "Bikaku"], "Uma vez por sessão, por 3 turnos: +2 caudas temporárias, +3 dano, +2 defesa e +1 alcance; o primeiro erro inimigo por rodada permite ataque de cauda com metade dos dados.", 12),

  quimera("serafim-ferro-sangue", "Serafim de Ferro e Sangue", 20, ["Ukaku", "Koukaku", "Rinkaku"], "Uma vez por turno escolha Asas (+2 Esquiva), Armadura (+3 RD) ou Tentáculos (+3 dano corpo a corpo).", 10),
  quimera("motor-cerco-celeste", "Motor de Cerco Celeste", 25, ["Ukaku", "Koukaku", "Bikaku"], "Após percorrer metade do Deslocamento e parar em posição estável: próximo ataque +2 acerto e dano; se não mover no turno seguinte, +2 RD.", 10),
  quimera("predador-cem-vetores", "Predador de Cem Vetores", 25, ["Ukaku", "Rinkaku", "Bikaku"], "Após acertar, escolha outro inimigo: o próximo ataque contra ele recebe +2 acerto, sem retornar ao alvo anterior pelo mesmo efeito.", 10),
  quimera("leviata-carne", "Leviatã de Carne", 25, ["Koukaku", "Rinkaku", "Bikaku"], "Ao sofrer dano, uma vez por rodada escolha +2 RD até o próximo turno, recuperar 2 RC ou +2 dano no próximo ataque; não repita em rodadas seguidas.", 10),
  quimera("trindade-predatoria", "Trindade Predatória", 30, [], "Escolha aspectos de três tipos; a cada turno, mantenha dois: Ukaku +2 acerto à distância, Koukaku +3 RD, Rinkaku +2 dano e +1 testes biológicos, Bikaku +2 defesa corpo a corpo.", 12, { minKaguneTypes: 3, requirement: "Qualquer Quimera Tripla; Grau 12+" }),
  quimera("quimera-absoluta", "Quimera Absoluta", 40, ["Ukaku", "Koukaku", "Rinkaku", "Bikaku"], "Uma vez por sessão, por 3 turnos: +3 acerto, +4 dano, +4 RD, +2 Esquiva e +1 alcance; primeira habilidade ativa custa -2 RC. Depois perca 20 RC e desative a Kagune por 2 turnos.", 12),

  hybrid("impacto-cinetico", "Impacto Cinético", 5, { forca: 4, agilidade: 4 }, "Uma vez por turno, após mover ao menos 1 espaço, o ataque corpo a corpo recebe +2 dados de dano."),
  hybrid("predador-impacto", "Predador de Impacto", 8, { forca: 7, agilidade: 7 }, "Após percorrer metade do Deslocamento, o próximo ataque corpo a corpo recebe +2 acerto e empurra 1 espaço se causar dano."),
  hybrid("vetor-perfeito", "Vetor Perfeito", 5, { forca: 4, precisao: 4 }, "Reduza em 1 dado a penalidade de acerto ao mirar partes específicas."),
  hybrid("cirurgiao-guerra", "Cirurgião de Guerra", 8, { forca: 7, precisao: 7 }, "Ao superar a defesa em 2 acertos, uma vez por turno escolha +2 dano, ignorar 2 RD ou impedir Reação."),
  hybrid("corpo-cerco", "Corpo de Cerco", 6, { forca: 5, vigor: 5 }, "Ao Bloquear e zerar o dano, o próximo ataque corpo a corpo recebe +3 dados de dano."),
  hybrid("colosso", "Colosso", 10, { forca: 8, vigor: 8 }, "Conte como uma categoria de tamanho acima e receba +2 dados em empurrões, agarrões e resistência a deslocamento."),
  hybrid("cacador-aberturas", "Caçador de Aberturas", 6, { forca: 5, percepcao: 5 }, "Quando inimigo errar ataque corpo a corpo, seu próximo golpe contra ele recebe +1 acerto e +2 dano."),
  hybrid("freio-impacto", "Freio de Impacto", 6, { forca: 5, controle: 5 }, "Você pode conter empurrões ou destruição causados pela força e ganhar +1 dado de acerto naquele golpe."),
  hybrid("tiro-movimento", "Tiro em Movimento", 5, { agilidade: 4, precisao: 4 }, "Mover-se antes de disparar não impõe penalidade comum; após metade do Deslocamento, +1 dado no primeiro ataque à distância."),
  hybrid("linha-impossivel", "Linha Impossível", 10, { agilidade: 8, precisao: 8 }, "Após mover 2 espaços, reduza em 2 dados penalidades de cobertura, ângulo ou posição no próximo ataque."),
  hybrid("reflexo-predatorio", "Reflexo Predatório", 6, { agilidade: 5, percepcao: 5 }, "A primeira Esquiva contra inimigo visível recebe +1 dado; ao passar, identifique a direção do ataque."),
  hybrid("janela-decimo", "Janela de 0,1 Segundo", 10, { agilidade: 8, percepcao: 8 }, "Uma vez por rodada, após Esquiva bem-sucedida, receba +2 dados no próximo ataque contra o inimigo."),
  hybrid("trajetoria-prevista", "Trajetória Prevista", 6, { agilidade: 5, raciocinio: 5 }, "Após observar inimigo por um turno, +1 dado de Esquiva até ele mudar drasticamente o padrão."),
  hybrid("corpo-elastico", "Corpo Elástico", 6, { agilidade: 5, vigor: 5 }, "Reduza em 2 dados penalidades por quedas, impactos ou aterrissagens; levantar-se não reduz movimento uma vez por turno."),
  hybrid("coordenacao-absoluta", "Coordenação Absoluta", 6, { precisao: 5, percepcao: 5 }, "Contra inimigo percebido claramente que ainda não agiu na rodada, receba +2 dados de acerto."),
  hybrid("olho-mao-monstro", "Olho-Mão de Monstro", 10, { precisao: 8, percepcao: 8 }, "Após obter 3 acertos em ataque, o próximo contra o mesmo alvo reduz uma penalidade de acerto em 1 dado."),
  hybrid("balistica-mental", "Balística Mental", 6, { precisao: 5, raciocinio: 5 }, "Após uma Ação analisando o ambiente, o próximo ataque à distância reduz até 2 dados de cobertura ou obstáculos previsíveis."),
  hybrid("equacao-letal", "Equação Letal", 10, { precisao: 8, raciocinio: 8 }, "Uma vez por descanso, converta até 2 dados de acerto em +2 dados de dano cada; o uso é gasto mesmo em erro."),
  hybrid("nervos-aco", "Nervos de Aço", 5, { vigor: 4, controle: 4 }, "Com metade ou menos da Vida, +1 dado em Vigor contra condições e +1 Controle contra medo, dor ou impulsos."),
  hybrid("dor-comando", "Dor Sob Comando", 8, { vigor: 7, controle: 7 }, "Uma vez por combate, ignore por 2 turnos penalidades temporárias de ferimentos; o dano permanece."),
  hybrid("metabolismo-calculado", "Metabolismo Calculado", 6, { vigor: 5, raciocinio: 5 }, "Uma vez por descanso ao receber cura, recupere +2 Vida ou +1 RC."),
  hybrid("instinto-somatico", "Instinto Somático", 6, { vigor: 5, percepcao: 5 }, "Na primeira exposição da cena a veneno, doença, droga ou efeito biológico hostil, reconheça a alteração e receba +2 dados para resistir."),
  hybrid("leitura-vetorial", "Leitura Vetorial", 6, { raciocinio: 5, percepcao: 5 }, "Após uma Ação observando inimigo, até o próximo turno receba +1 defesa e +1 acerto contra ele."),
  hybrid("campo-batalha", "Campo de Batalha", 10, { raciocinio: 8, percepcao: 8 }, "Escolha uma característica do terreno; ao explorá-la coerentemente, receba +2 dados em um tipo de teste aprovado. Mude com uma Ação."),
  hybrid("mente-guerra", "Mente de Guerra", 6, { raciocinio: 5, controle: 5 }, "Uma vez por descanso, após falhar em combate, ganhe +2 dados na próxima tentativa semelhante da cena."),
  hybrid("sangue-frio", "Sangue Frio", 10, { raciocinio: 8, controle: 8 }, "Uma vez por cena, após testar normalmente, negue penalidade mecânica de provocação, medo, confusão ou manipulação em combate."),
  hybrid("calma-cacador", "Calma do Caçador", 6, { percepcao: 5, controle: 5 }, "Após um turno sem atacar, o próximo ataque recebe +2 dados de acerto; atacar outro alvo remove o bônus."),
  hybrid("autoridade-inabalavel", "Autoridade Inabalável", 6, { presenca: 5, controle: 5 }, "Aliados que ouvem você ganham +1 dado no primeiro teste contra medo ou hesitação da cena."),
  hybrid("rei-inferno", "Rei no Inferno", 10, { presenca: 8, controle: 8 }, "Com metade ou menos da Vida, inimigos sofrem -1 dado na primeira tentativa por turno de intimidar, manipular ou forçar sua retirada."),
  hybrid("xadrez-social", "Xadrez Social", 6, { presenca: 5, raciocinio: 5 }, "Após alguns minutos de conversa, identifique a abordagem social mais eficiente; o próximo teste de Presença usando-a recebe +2 dados."),
  hybrid("leitor-sala", "Leitor de Sala", 6, { presenca: 5, percepcao: 5 }, "Ao entrar em cena social, identifique rapidamente autoridade, desconforto e pessoas deslocadas; revela impressões, não segredos."),

  combat("especialista-manobras", "Especialista em Manobras", 4, "Uma vez por turno, reduza em 1 dado a penalidade de acerto de Derrubar, Desarmar ou manobra semelhante."),
  combat("guarda-fechada", "Guarda Fechada", 5, "Ao passar o turno sem atacar, receba +2 RD até o próximo turno."),
  combat("oportunista", "Oportunista", 5, "Uma vez por rodada, ataques de oportunidade recebem +2 dados de dano."),
  combat("cacador-reacoes", "Caçador de Reações", 6, "Quando inimigo gastar a Reação, o próximo ataque contra ele naquele turno recebe +1 acerto."),
  combat("quebrador-ritmo", "Quebrador de Ritmo", 6, "Ao acertar inimigo com bônus por sequência, movimento ou postura, reduza um acúmulo em 1, uma vez por turno."),
  combat("guarda-agressiva", "Guarda Agressiva", 6, "Após bloquear completamente ataque corpo a corpo, o próximo ataque contra o agressor recebe +2 dados de dano."),
  combat("contra-passo", "Contra-Passo", 6, "Após Esquiva bem-sucedida, mova 1 espaço em direção ao atacante em vez de se afastar, uma vez por rodada."),
  combat("demolidor-defesa", "Demolidor de Defesa", 8, "Ao causar dano após RD em corpo a corpo, o próximo ataque de aliado contra o alvo ignora 2 RD, uma vez por turno."),
  combat("ritmo-combate", "Ritmo de Combate", 8, "Após acertar em três turnos consecutivos, ganhe +1 acerto e +1 dano até errar todos os ataques de um turno ou não atacar."),
  combat("carrasco", "Carrasco", 8, "Contra inimigos com 1/4 ou menos da Vida, receba +2 dados de dano."),
  combat("ainda-nao-acabou", "Ainda Não Acabou", 8, "Uma vez por descanso, ao sofrer crítico, ganhe +2 dados no primeiro teste ofensivo ou defensivo do próximo turno."),
  combat("dominio-espaco", "Domínio de Espaço", 10, "Inimigos no seu alcance corpo a corpo sofrem -1 dado para passar por você ou abandonar o alcance sem proteção.", 8),
  combat("duelo-monstros", "Duelo de Monstros", 10, "Escolha inimigo no começo da cena: +1 acerto e defesa contra ele até outro inimigo acertar você.", 8),
  combat("ultimo-homem-pe", "Último Homem de Pé", 12, "Uma vez por sessão, quando todos os aliados estiverem incapacitados, por 3 turnos receba +2 acerto, defesa e dano.", 10),
];

export const expansionEvolutions: Evolution[] = [
  { id: "reator-rc", name: "Reator de RC", cost: 15, grade: 8, family: "Quimera", minKaguneTypes: 2, requirement: "Qualquer Quimera; Grau 8+", description: "Uma vez por turno, ao usar propriedades de dois tipos no mesmo ataque, recupere 1 RC após a resolução, até 3 RC por turno." },
  { id: "sincronia-kakuhous", name: "Sincronia das Kakuhous", cost: 20, grade: 10, family: "Quimera", minKaguneTypes: 2, requirement: "Qualquer Quimera; Grau 10+", description: "Escolha duas vantagens passivas de tipos diferentes: enquanto ambas estiverem manifestadas, cada uma recebe benefício equivalente a +1 dado, +1 RD ou +1 dado de dano, nunca Passos." },
  { id: "forma-quimerica-perfeita", name: "Forma Quimérica Perfeita", cost: 25, grade: 10, family: "Quimera", minKaguneTypes: 2, requirement: "Quimera; Grau 10+", description: "Uma vez por cena, gaste 10 RC: por 3 turnos, utilize duas Mudanças de Forma de tipos diferentes ao mesmo tempo; bônus equivalentes usam apenas o maior." },
  { id: "evolucao-cruzada", name: "Evolução Cruzada", cost: 25, grade: 12, family: "Quimera", minKaguneTypes: 2, requirement: "Quimera; Grau 12+", description: "Escolha Evolução exclusiva de Grau 8 ou menor de um de seus tipos e integre característica secundária do outro, ampliando versatilidade sem duplicar bônus numéricos." },
  { id: "monstro-nao-escolheu", name: "O Monstro Não Escolheu", cost: 35, grade: 12, family: "Quimera", minKaguneTypes: 2, requirement: "Quimera; Grau 12+; uma vez por sessão", description: "Por 3 turnos, escolha dois aspectos por turno: +4 dano, +3 Esquiva, +3 acerto, +5 RD, alcance +1 e +2 dano à distância, ou primeira cura biológica +25%. Não repita a dupla; depois perca 15 RC e ganhe +1 Fome." },
];
