"use client";
import {useState} from 'react';
import type {KakujaState} from './kakuja-data';
import {kakujaPerks,kakujaPerkMissing,kakujaPerksCost,normalizeKakujaPerks,type KakujaPerk} from './kakuja-perks';
export function KakujaPerksPanel({state,grade,species,onChange}:{state:KakujaState;grade:number;species:string;onChange:(state:KakujaState)=>void}) {
 const [search,setSearch]=useState(''),[category,setCategory]=useState('Todas'),[ownedOnly,setOwnedOnly]=useState(false),[limit,setLimit]=useState(30);
 const selected=normalizeKakujaPerks(state.selectedPerks),q=search.trim().toLocaleLowerCase('pt-BR');
 const items=kakujaPerks.filter(p=>(category==='Todas'||p.category===category)&&(!ownedOnly||selected.includes(p.id))&&(!q||`${p.sourceId} ${p.name} ${p.effect} ${p.requirement}`.toLocaleLowerCase('pt-BR').includes(q)));
 const toggle=(p:KakujaPerk)=>{if(selected.includes(p.id))onChange({...state,selectedPerks:selected.filter(id=>id!==p.id)});else if(!kakujaPerkMissing(p,state,grade,species).length)onChange({...state,selectedPerks:[...selected,p.id]});};
 return <div className="kakuja-tab-content" role="tabpanel" aria-label="Novas perks de Kakuja"><section className="section-block compact kakuja-perks-intro"><h2>Perks de Kakuja</h2><p className="section-help">300 perks em 12 categorias. Compra única em PE comum, pelo valor indicado; 0 CM. Os custos entram no total da ficha.</p></section><div className="catalog-toolbar kakuja-toolbar"><label className="search-field"><span>⌕</span><input aria-label="Buscar perks de Kakuja" placeholder="Nome, código ou efeito" value={search} onChange={e=>{setSearch(e.target.value);setLimit(30);}}/></label><select aria-label="Categoria das perks de Kakuja" value={category} onChange={e=>{setCategory(e.target.value);setLimit(30);}}>{['Todas',...new Set(kakujaPerks.map(p=>p.category))].map(c=><option key={c}>{c}</option>)}</select></div><label className="vats-check"><input type="checkbox" checked={ownedOnly} onChange={e=>{setOwnedOnly(e.target.checked);setLimit(30);}}/>Somente compradas</label><div className="catalog-summary"><span>{items.length} perks nesta seleção</span><strong>{selected.length} compradas · {kakujaPerksCost(selected)} PE</strong></div><div className="catalog-grid kakuja-module-grid">{items.slice(0,limit).map(p=>{const purchased=selected.includes(p.id),missing=kakujaPerkMissing(p,state,grade,species);return <article key={p.id} className={`catalog-card kakuja-module-card ${purchased?'selected':''} ${missing.length?'unavailable':''}`}><div className="catalog-card-top"><span>{p.category} · #{p.sourceId}</span><b>{p.cost} PE</b></div><h3>{p.name}</h3><p>{p.effect}</p><div className="kakuja-card-meta"><span>Grau {p.grade}+</span><span>{p.cm} CM</span><span>{p.usage}</span></div><div className="requirement">{p.requirement}{missing.map(m=><em key={m}>Falta: {m}</em>)}{purchased&&!state.active&&<em>Ative a Kakuja antes de usar.</em>}</div><div className="card-actions solo"><button type="button" className={purchased?'remove':'add'} disabled={!purchased&&missing.length>0} onClick={()=>toggle(p)}>{purchased?'Remover':'Comprar'}</button></div></article>;})}</div>{items.length>limit&&<button type="button" className="text-button" onClick={()=>setLimit(limit+30)}>Mostrar mais 30 ({Math.min(limit,items.length)} de {items.length})</button>}{!items.length&&<p>Nenhuma perk encontrada.</p>}</div>;
}
