"use client";
import {useState} from 'react';
import {attributeKeys,attributeLabels,evolutions,kaguneEffects,perks,type KaguneFamily} from './data';
import {CustomSkillsPanel} from './CustomSkillsPanel';
import {advanceGradeIfReady,cumulativeGradePE,effectMaximum,evolutionCostsForSheet,formatTest,incrementalCosts,normalizeCharacter,registerEarnedPE} from './page';
import {calculateQuinque,normalizeQuinque,quinqueAllowsEffect,quinqueAllowsEvolution,quinqueAllowsPerk,quinqueEffectMissing,quinqueEvolutionMissing,quinquePerkMissing,type Quinque} from './quinque';

function Numeric({label,value,onChange,nullable=false,min}:{label:string;value:number|null;onChange:(value:number|null)=>void;nullable?:boolean;min?:number}) {
 return <label className="field"><span>{label}</span><input type="number" min={min} value={value??''} placeholder={nullable?'Automático':undefined} onChange={e=>onChange(nullable&&e.target.value===''?null:Number(e.target.value)||0)} /></label>;
}
export function QuinquesPanel({items,selectedId,onSelect,onChange}:{items:Quinque[];selectedId:string;onSelect:(id:string)=>void;onChange:(items:Quinque[])=>void}) {
 const [view,setView]=useState('efeitos'),[query,setQuery]=useState(''),[gain,setGain]=useState(0),[removed,setRemoved]=useState<Quinque|null>(null),[copied,setCopied]=useState(false);
 const q=items.find(x=>x.id===selectedId)||items[0];
 if(!q)return <section className="section-block"><h2>Suas Quinques</h2><p>Adicione uma Quinque para definir seu Grau, tipo de RC, atributos e melhorias. Cada arma tem seu próprio orçamento.</p>{removed&&<button type="button" onClick={()=>{onChange([...items,removed]);onSelect(removed.id);setRemoved(null);}}>Desfazer remoção de {removed.name}</button>}</section>;
 const patch=(next:Partial<Quinque>)=>onChange(items.map(x=>x.id===q.id?normalizeQuinque({...q,...next}):x));
 const d=calculateQuinque(q);
 const test=formatTest(Number(d.kaguneTest.match(/^\d+/)?.[0]||1),d.hitModifier);
 const matches=(x:{name:string;description:string})=>`${x.name} ${x.description}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'));
 const effectItems=kaguneEffects.filter(e=>quinqueAllowsEffect(q,e)&&matches(e));
 const evolutionItems=evolutions.filter(e=>quinqueAllowsEvolution(q,e)&&matches(e));
 const perkItems=perks.filter(p=>quinqueAllowsPerk(q,p)&&matches(p));
 const invalid=[...d.invalidEffects,...d.invalidEvolutions,...d.invalidPerks];
 return <div className="page-stack quinques-panel">
  <div className="filter-row quinque-picker" aria-label="Selecionar Quinque">{items.map(item=><button type="button" key={item.id} className={item.id===q.id?'active':''} onClick={()=>{onSelect(item.id);setQuery('');}}>{item.name||'Sem nome'} · {item.rcType} · G{item.grade}</button>)}</div>
  <section className="section-block"><div className="attribute-section-head"><div><span>Quinque independente</span><p>Grau, atributos e PE pertencem a esta arma. Efeitos universais e de {q.rcType}; sem acesso a outros tipos de RC.</p></div><button type="button" className="text-button" onClick={()=>{setRemoved(q);onChange(items.filter(x=>x.id!==q.id));}}>Remover Quinque</button></div>
   {removed&&<button type="button" onClick={()=>{onChange([...items,removed]);onSelect(removed.id);setRemoved(null);}}>Desfazer remoção de {removed.name}</button>}
   <div className="field-grid four"><label className="field"><span>Nome da Quinque</span><input value={q.name} onChange={e=>patch({name:e.target.value})} /></label><label className="field"><span>Tipo de RC da Quinque</span><select aria-label="Tipo de RC da Quinque" value={q.rcType} onChange={e=>patch({rcType:e.target.value as KaguneFamily})}>{['Ukaku','Koukaku','Rinkaku','Bikaku'].map(t=><option key={t}>{t}</option>)}</select></label><label className="field"><span>Grau da Quinque</span><select aria-label="Grau da Quinque" value={q.grade} onChange={e=>patch({grade:Number(e.target.value),progressPE:0,earnedPE:0})}>{[2,4,6,8,10,12,14].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label className="field"><span>Grau do Ghoul de criação</span><select aria-label="Grau do Ghoul de criação" value={q.creationGrade} onChange={e=>patch({creationGrade:Number(e.target.value)})}>{[2,4,6,8,10,12,14].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div>
   <div className="weapon-metrics"><div className="stat"><span>PE disponíveis</span><strong>{d.available}</strong></div><div className="stat"><span>PE investidos</span><strong>{d.spent}</strong></div><div className="stat"><span>PE restantes</span><strong>{d.remaining}</strong></div><div className="stat"><span>Acerto próprio</span><strong>{test}</strong></div></div>
   <p className="section-help">Base: 8 + {q.creationGrade} de criação. Progressão acumulada do Grau: {cumulativeGradePE(q.grade)} PE. Atributos e habilidades são pagos pelo saldo desta Quinque.</p>
   <div className="field-grid four"><Numeric label="PE bônus da Quinque" value={q.bonusPE} onChange={n=>patch({bonusPE:n||0})}/><Numeric label="PE ganhos agora" value={gain} min={0} onChange={n=>setGain(Math.max(0,n||0))}/></div><div className="card-actions"><button type="button" disabled={gain<=0} onClick={()=>{patch(registerEarnedPE(q,gain));setGain(0);}}>Registrar PE na Quinque</button><button type="button" disabled={!d.nextGradePE||q.progressPE<d.nextGradePE} onClick={()=>patch(advanceGradeIfReady(q))}>Evoluir Quinque{d.nextGradePE?` · ${q.progressPE}/${d.nextGradePE} PE`:' · Grau máximo'}</button></div>
   {d.remaining<0&&<p className="vats-warning" role="status">Esta Quinque excede seu orçamento em {Math.abs(d.remaining)} PE.</p>}
  </section>
  <section className="section-block"><h2>Atributos da Quinque</h2><p className="section-help">Valores próprios da arma, separados dos atributos do portador. O atributo de acerto é {attributeLabels[d.primaryAttribute]}.</p><div className="field-grid four">{attributeKeys.map(k=><Numeric key={k} label={`${attributeLabels[k]} da Quinque`} value={q.attributes[k]} min={0} onChange={n=>patch({attributes:{...q.attributes,[k]:n||0}})}/>)}</div></section>
  <section className="section-block"><h2>Combate e ajustes personalizados</h2><div className="weapon-metrics"><div className="stat"><span>Dano</span><strong>{d.kaguneDamage}</strong></div><div className="stat"><span>RD da arma</span><strong>{d.rd}</strong></div><div className="stat"><span>Dureza da arma</span><strong>{d.durability}</strong></div><div className="stat"><span>Alcance</span><strong>{d.distance} m</strong></div></div><div className="card-actions"><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(test);setCopied(true);window.setTimeout(()=>setCopied(false),1200);}catch{setCopied(false);}}}>{copied?'Copiado!':'Copiar acerto da Quinque'}</button><button type="button" onClick={()=>navigator.clipboard.writeText(d.kaguneDamage).catch(()=>undefined)}>Copiar dano da Quinque</button></div>
   <p className="section-help">RD e Dureza personalizadas substituem o total automático; deixe em branco para usar o cálculo. Os demais ajustes são somados. Estes valores não alteram a ficha do portador.</p>
   <div className="field-grid four"><Numeric label="RD personalizada" value={q.rdOverride} nullable min={0} onChange={n=>patch({rdOverride:n})}/><Numeric label="Dureza personalizada" value={q.durabilityOverride} nullable min={0} onChange={n=>patch({durabilityOverride:n})}/><Numeric label="Dados extras de acerto" value={q.hitDice} onChange={n=>patch({hitDice:n||0})}/><Numeric label="Modificador extra de acerto" value={q.hitModifier} onChange={n=>patch({hitModifier:n||0})}/><Numeric label="Passos extras de dano" value={q.damageSteps} onChange={n=>patch({damageSteps:n||0})}/><Numeric label="Modificador extra de dano" value={q.damageModifier} onChange={n=>patch({damageModifier:n||0})}/><Numeric label="Alcance extra em metros" value={q.rangeBonus} onChange={n=>patch({rangeBonus:n||0})}/></div>
   {q.effects['forma-versatil']&&q.rcType==='Koukaku'&&<label className="field"><span>Forma Versátil</span><select value={q.mode} onChange={e=>patch({mode:e.target.value as Quinque['mode']})}><option value="normal">Normal</option><option value="attack">Lâmina</option><option value="defense">Escudo</option></select></label>}
   {Object.keys(q.effects).filter(id=>!d.invalidEffects.includes(id)&&kaguneEffects.find(e=>e.id===id)?.type.startsWith('Ativo')).map(id=><label className="requirement-confirm" key={id}><input type="checkbox" checked={!!q.activeEffects[`kagune:${id}`]} onChange={e=>patch({activeEffects:{...q.activeEffects,[`kagune:${id}`]:e.target.checked}})}/><span>Aplicar {kaguneEffects.find(e=>e.id===id)?.name} neste golpe</span></label>)}
   <p className="section-help">Efeitos que exigem escolha de alvo, gatilho ou sacrifício de dados continuam seguindo a descrição da técnica.</p>
  </section>
  {invalid.length>0&&<section className="section-block"><h2>Compras que precisam de revisão</h2><p>Estas compras foram preservadas, mas não aplicam bônus enquanto forem incompatíveis com o tipo, Grau ou requisitos. Você pode removê-las para recuperar o PE.</p>{invalid.map(id=><div className="card-actions" key={id}><span>{[...kaguneEffects,...evolutions,...perks].find(e=>e.id===id)?.name||id}</span><button type="button" onClick={()=>{const effects={...q.effects},selectedPerks={...q.perks};delete effects[id];delete selectedPerks[id];patch({effects,perks:selectedPerks,evolutions:q.evolutions.filter(x=>x!==id)});}}>Remover compra incompatível</button></div>)}</section>}
  <section className="section-block"><h2>Habilidades desta Quinque</h2><div className="filter-row">{[['efeitos','Efeitos'],['evolucoes','Evoluções'],['perks','Perks de Quinque'],['autorais','Habilidades autorais']].map(([id,label])=><button type="button" key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</div>
   {view==='autorais'?<CustomSkillsPanel skills={q.customSkills} onChange={customSkills=>patch({customSkills})}/>:<><label className="search-field"><input aria-label="Buscar habilidades da Quinque" placeholder="Buscar habilidade" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="catalog-grid effects">
    {view==='efeitos'&&effectItems.map(e=>{const rank=q.effects[e.id]?.rank||0;const max=effectMaximum(e,normalizeCharacter({quinques:[],grade:q.grade,kaguneType:q.rcType}));const missing=quinqueEffectMissing(q,e,Math.max(1,rank));const change=(next:number)=>{if(next>0&&quinqueEffectMissing(q,e,next).length)return;const effects={...q.effects};if(next)effects[e.id]={rank:next};else delete effects[e.id];patch({effects});};return <article key={e.id} className={`catalog-card ${rank?'selected':''}`}><div className="catalog-card-top"><span>{e.family} · {e.type}</span><b>{incrementalCosts(e,Math.max(1,rank)).reduce((a,b)=>a+b,0)} PE</b></div><h3>{e.name}</h3><p>{e.description}</p><div className="requirement">{missing.join(' · ')}</div><div className="card-actions">{rank>0&&max>1&&<div className="rank-control"><button type="button" disabled={rank<=1} onClick={()=>change(rank-1)}>−</button><span>N{rank}/{max}</span><button type="button" disabled={rank>=max||!!quinqueEffectMissing(q,e,rank+1).length} onClick={()=>change(rank+1)}>+</button></div>}<button type="button" disabled={!rank&&!!missing.length} onClick={()=>change(rank?0:1)}>{rank?'Remover':'Comprar'}</button></div></article>;})}
    {view==='evolucoes'&&evolutionItems.map(e=>{const rank=q.evolutions.filter(x=>x===e.id).length,max=e.maxRank||1;const missing=quinqueEvolutionMissing(q,e,Math.max(1,rank));const change=(next:number)=>{if(next>0&&quinqueEvolutionMissing(q,e,next).length)return;patch({evolutions:[...q.evolutions.filter(x=>x!==e.id),...Array.from({length:next},()=>e.id)]});};return <article key={e.id} className={`catalog-card ${rank?'selected':''}`}><div className="catalog-card-top"><span>{e.family} · Grau {e.grade}+</span><b>{evolutionCostsForSheet(e,Math.max(1,rank),'ghoul').paidTotal} PE</b></div><h3>{e.name}</h3><p>{e.description}</p><div className="requirement">{e.requirement}{missing.map(m=><em key={m}>{m}</em>)}</div>{e.narrativeRequirement&&<label className="requirement-confirm"><input type="checkbox" checked={!!q.confirmedRequirements[`evolution:${e.id}`]} onChange={event=>patch({confirmedRequirements:{...q.confirmedRequirements,[`evolution:${e.id}`]:event.target.checked}})}/><span>Requisito narrativo confirmado</span></label>}<div className="card-actions">{rank>0&&max>1&&<div className="rank-control"><button type="button" disabled={rank<=1} onClick={()=>change(rank-1)}>−</button><span>N{rank}/{max}</span><button type="button" disabled={rank>=max||!!quinqueEvolutionMissing(q,e,rank+1).length} onClick={()=>change(rank+1)}>+</button></div>}<button type="button" disabled={!rank&&!!missing.length} onClick={()=>change(rank?0:1)}>{rank?'Remover':'Comprar'}</button></div></article>;})}
    {view==='perks'&&perkItems.map(p=>{const owned=!!q.perks[p.id],missing=quinquePerkMissing(q,p);return <article key={p.id} className={`catalog-card ${owned?'selected':''}`}><div className="catalog-card-top"><span>Quinque · Grau {p.minGrade||2}+</span><b>{typeof p.cost==='number'?p.cost:p.cost[0]} PE</b></div><h3>{p.name}</h3><p>{p.description}</p><div className="requirement">{missing.join(' · ')}</div><button type="button" disabled={!owned&&!!missing.length} onClick={()=>{const next={...q.perks};if(owned)delete next[p.id];else next[p.id]={rank:1};patch({perks:next});}}>{owned?'Remover':'Comprar'}</button></article>;})}
   </div></>}
  </section><section className="section-block"><label className="field"><span>Descrição e notas da Quinque</span><textarea value={q.notes} onChange={e=>patch({notes:e.target.value})}/></label></section>
 </div>;
}

