"use client";
import { useState } from "react";
import type { Perk } from "./data";

export function SupplementRules() {
 return <details className="section-block compact"><summary>Mil novas perks · regras do suplemento</summary><p className="section-help">Compra única pelo PE indicado. Requisitos de Grau arredondados para o próximo par. Cada vantagem está associada a um atributo ou à estrutura correspondente; essa organização não cria um requisito de atributo.</p><p className="section-help">Os efeitos são situacionais e resolvidos na mesa conforme o texto. Não somam automaticamente RC máximo ou Dureza. Órgãos e equipamentos exigidos precisam estar manifestados e funcionais para usar a técnica; Kakuja precisa estar ativa. Condições específicas de cada entrada continuam obrigatórias.</p><p className="section-help">Salvo exceção escrita: uma ativação por rodada e uma reação especial de perk por rodada. Bônus expiram no início do próximo turno. Entre perks deste suplemento, limites de +3 dados por teste, +4 RD, +4 dano fixo e +1 Passo; valores maiores expressos valem sozinhos. Cópias não acumulam. Ataques extras não geram outros ataques extras; use apenas a maior redução de custo. Reservas começam em zero e acabam com a cena, salvo texto diferente. Dívidas permanecem. Recuperações respeitam os máximos e exigem risco real. Custos RC escritos são finais.</p></details>;
}

export function SupplementOrganPerks({items,owned,eligible,onToggle}:{items:Perk[];owned:(id:string)=>boolean;eligible:(item:Perk)=>boolean;onToggle:(item:Perk)=>void}) {
 const [group,setGroup]=useState('Todos'),[limit,setLimit]=useState(40),[localSearch,setLocalSearch]=useState('');
 const query=localSearch.trim().toLocaleLowerCase('pt-BR');
 const matches=items.filter(p=>(group==='Todos'||p.organGroup===group)&&(!query||`${p.sourceId} ${p.name} ${p.description} ${p.requirement}`.toLocaleLowerCase('pt-BR').includes(query)));
 return <section><div className="attribute-section-head"><div><span>Novas perks · Kakuhou & arma</span><p>400 técnicas de órgãos e equipamentos · compras independentes em PE</p></div></div><SupplementRules/><label className="search-field"><span>⌕</span><input aria-label="Buscar novas perks de Kakuhou" placeholder="Nome, código ou efeito da perk" value={localSearch} onChange={e=>{setLocalSearch(e.target.value);setLimit(40);}}/></label><div className="filter-row">{['Todos','Ukaku','Koukaku','Rinkaku','Bikaku','Quimera','Kakuja','Quinque','Quinx / Arata'].map(g=><button type="button" key={g} className={g===group?'active':''} onClick={()=>{setGroup(g);setLimit(40);}}>{g}</button>)}</div><div className="catalog-summary"><span>{matches.length} opções · {items.filter(p=>owned(p.id)).length} adquiridas</span></div><div className="catalog-grid effects">{matches.slice(0,limit).map(p=>{const selected=owned(p.id),allowed=eligible(p);return <article key={p.id} className={`catalog-card ${selected?'selected':''} ${!allowed?'unavailable':''}`}><div className="catalog-card-top"><span>{p.organGroup} · {p.useType} · {p.sourceId}</span><b>{p.cost} PE</b></div><h3>{p.name}</h3><p>{p.description}</p><div className="requirement">{p.requirement}<em>Fonte: Mil novas perks, p. {p.sourcePage}</em>{!allowed&&<em>Requisito pendente: confira Grau, estrutura e desbloqueios.</em>}</div><div className="card-actions"><button type="button" className={selected?'remove':'add'} disabled={!allowed&&!selected} onClick={()=>onToggle(p)}>{selected?'Remover':'Adicionar'}</button></div></article>;})}</div>{matches.length>limit&&<button type="button" className="text-button" onClick={()=>setLimit(limit+40)}>Mostrar mais 40 perks ({Math.min(limit,matches.length)} de {matches.length})</button>}{!matches.length&&<p className="section-help">Nenhuma perk encontrada neste filtro.</p>}</section>;
}
