"use client";
import { useState } from 'react';
import { regions, injuryGroups, injuryByName, penalties, passivePreview, adjustTest, type RegionId, type VatsState, type VatsConfig, type VatsAction } from './vats-engine';

const shapes:Record<RegionId,string>={
 head:'M140 23 Q115 23 117 49 L123 69 135 78 146 78 158 68 164 45 Q164 23 140 23Z',
 torso:'M128 81 L152 81 172 93 168 137 160 171 164 202 146 215 134 215 116 202 120 171 112 137 108 93Z',
 armL:'M175 94 Q190 94 193 113 L199 154 211 196 207 215 194 218 187 203 186 177 174 146 169 119Z',
 armR:'M105 94 Q90 94 87 113 L81 154 69 196 73 215 86 218 93 203 94 177 106 146 111 119Z',
 legL:'M147 219 L164 207 168 244 160 278 158 309 155 349 164 360 162 370 143 371 138 361 137 322 141 286 139 253Z',
 legR:'M133 219 L116 207 112 244 120 278 122 309 125 349 116 360 118 370 137 371 142 361 143 322 139 286 141 253Z',
};
export function VatsPanel({state:v,config:c,name,onAction:act}:{state:VatsState;config:VatsConfig;name:string;onAction:(a:VatsAction)=>void}){
 const [selected,setSelected]=useState<RegionId>('torso'),[amount,setAmount]=useState(5),[effect,setEffect]=useState(''),[useRD,setUseRD]=useState(false),[enemy,setEnemy]=useState(true),[confirm,setConfirm]=useState('');
 const r=v.body[selected],region=regions.find(x=>x[0]===selected)!,w=penalties(v),preview=passivePreview(v,c);
 const hp=(id:RegionId)=>Math.max(0,c.maxLife-v.body[id].damage),pct=(id:RegionId)=>Math.round(hp(id)/c.maxLife*100);
 const choose=(id:RegionId)=>{setSelected(id);setEffect('');};
 const power=(id:string)=>c.powers.includes(id), blocked=c.rc<=0||w.exhausted;
 const actions=[...v.global,...r.effects];
 return <div className="page-stack vats-page">
  <header className="vats-heading"><div><span className="eyebrow">05 / ANÁLISE CORPORAL</span><h1>VATS<span>.</span></h1><p>{name||'Sem nome'} · Selecione uma região para tratar o dano.</p></div><div className="turn-control"><span>TURNO <b>{String(v.turn).padStart(2,'0')}</b></span><button type="button" onClick={()=>act({type:'turn'})}>Encerrar turno →</button><small>Aplica sangramentos e perdas de RC.</small></div></header>
  <div className="vats-readings"><div><span>PV / REGIÃO</span><b>{c.maxLife}</b></div><div><span>RESERVA RC</span><b>{Math.min(c.rc,c.maxRC)} <small>/ {c.maxRC}</small></b></div><div><span>REGENERAÇÃO</span><b>{preview.amount}<small> / turno</small></b></div><div><span>MOVIMENTO</span><b>{c.movement}<small> espaços</small></b></div></div>
  <div className="vats-layout">
   <section className="body-monitor" aria-label="Mapa corporal"><div className="monitor-caption"><span>INTEGRIDADE REGIONAL</span><span>ANTERIOR / 01</span></div><div className="anatomy">
    <div className="body-axis"/><svg viewBox="0 0 280 395" role="group" aria-label="Selecionar região do corpo"><defs><pattern id="hatch" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(35)"><line x1="0" y1="0" x2="0" y2="6" stroke="currentColor" strokeWidth="1" opacity=".2"/></pattern></defs>
     {regions.map(([id,label])=><g key={id} role="button" tabIndex={0} aria-label={`${label}: ${hp(id)} de ${c.maxLife} PV`} aria-pressed={selected===id} onClick={()=>choose(id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(id);}}} className={`anatomy-part ${selected===id?'selected':''} ${pct(id)<=25||v.body[id].destroyed?'critical':pct(id)<100||v.body[id].effects.length?'injured':''}`}><title>{label}</title><path d={shapes[id]}/><path d={shapes[id]} fill="url(#hatch)" className="hatching"/></g>)}
     <g className="anatomy-detail" fill="none"><path d="M140 95V160 M120 107L138 116 160 107 M121 118L138 126 159 118 M124 132L138 139 156 132 M128 148L138 153 152 148 M128 177L138 183 151 177 M127 188L140 199 153 188 M128 46H153 M129 58Q140 63 151 58"/></g>
    </svg>
    {regions.map(([id,label])=><button type="button" key={id} className={`body-label label-${id} ${selected===id?'selected':''} ${pct(id)<=25||v.body[id].destroyed?'critical':''}`} onClick={()=>choose(id)}><span>{label}</span><strong>{pct(id)}<small>%</small></strong><div className="integrity-bar"><i style={{width:`${pct(id)}%`}}/></div><small>{hp(id)} / {c.maxLife} PV · {v.body[id].destroyed?'destruído':v.body[id].effects.length?`${v.body[id].effects.length} efeitos`:'íntegro'}</small></button>)}
   </div><div className="monitor-legend"><span>● Íntegro</span><span>● Ferido</span><span>● Crítico</span></div><p className="monitor-footnote">Cada região usa a Vida máxima da ficha. Ferimentos permanecem ao trocar de aba ou personagem.</p></section>
   <section className="region-inspector"><span className="eyebrow">REGIÃO SELECIONADA</span><h2>{region[1]}</h2><div className="region-hp"><b>{hp(selected)}</b><span>/ {c.maxLife} PV</span><small>{r.destroyed?'DESTRUÍDO':pct(selected)<=25?'CRÍTICO':pct(selected)<100?'FERIDO':'ÍNTEGRO'}</small></div><div className="integrity-bar"><i style={{width:`${pct(selected)}%`}}/></div>
    <div className="damage-controls"><label>Quantidade<input aria-label="Quantidade de dano ou cura" type="number" min="0" value={amount} onChange={e=>setAmount(Math.max(0,Number(e.target.value)||0))}/></label><button type="button" className="blood-button" disabled={!amount} onClick={()=>act({type:'damage',region:selected,amount,reduceRD:useRD})}>Aplicar dano</button><button type="button" disabled={!amount||r.destroyed} onClick={()=>act({type:'heal',region:selected,amount})}>Curar</button></div>
    <label className="vats-check"><input type="checkbox" checked={useRD} onChange={e=>setUseRD(e.target.checked)}/>Descontar RD da ficha ({c.rd})<b>{Math.max(0,amount-(useRD?c.rd:0)-v.fortressBonus)} dano líquido</b></label>
    {r.effects.includes('Costelas Quebradas')&&<p className="vats-warning">Pancada no tronco: +1 Passo no dano do atacante antes de rolar.</p>}
    {v.fortressBonus>0&&<p className="vats-help">Fortaleza: +{v.fortressBonus} RD já descontados no próximo dano.</p>}<div className="region-minor"><button type="button" onClick={()=>act({type:r.destroyed?'rebuild':'destroy',region:selected})}>{r.destroyed?'Reconstruir · decisão da mesa':'Marcar região destruída'}</button></div>
    <div className="effect-picker"><label htmlFor="injury-select">Aplicar condição</label><select id="injury-select" value={effect} onChange={e=>setEffect(e.target.value)}><option value="">Escolha um efeito…</option>{[['blood','Sangue'],[region[2],'Região'],['global','Posicionamento e colapso']].map(([key,label])=><optgroup key={key} label={label}>{injuryGroups[key].map(([n])=><option key={n} value={n} disabled={actions.includes(n)}>{n}</option>)}</optgroup>)}</select>{effect&&<div className="injury-preview"><b>{injuryByName[effect][1]}</b><p>{injuryByName[effect][2]}</p><button type="button" onClick={()=>{act({type:'add',region:selected,effect});setEffect('');}}>Aplicar efeito</button></div>}</div>
    <div className="active-injuries" aria-live="polite">{actions.length?actions.map(n=><article key={n}><div><b>{n}</b><p>{injuryByName[n]?.[2]}</p></div><button type="button" aria-label={`Remover ${n}`} onClick={()=>act({type:'remove',region:selected,effect:n})}>×</button></article>):<p className="empty-injuries">Nenhuma condição nesta região.</p>}</div>
   </section>
  </div>
  <section className="vats-consequences"><div><span className="eyebrow">IMPACTO NA FICHA</span><h2>Condições em combate</h2></div><div className="consequence-grid"><p>Testes físicos <b>{w.physical}d</b></p><p>Testes mentais <b>{w.mental}d</b></p><p>Esquiva <b>{c.dodgeTest}</b></p><p>Bloqueio <b>{c.blockTest}</b></p><p>Ações <b>{w.actions??'normais'}</b></p><p>Reação <b>{w.reaction?'disponível':'indisponível'}</b></p></div>
   <ContextTest state={v} config={c} selected={selected}/>
   <p className="vats-help">Penalidades gerais já entram nos testes da ficha. Penalidades situacionais abaixo se aplicam apenas ao contexto indicado.</p>
   <div className="situational-effects">{regions.flatMap(([id,label])=>v.body[id].effects.map(n=><p key={id+n}><b>{label} · {n}</b><span>{injuryByName[n]?.[2]}</span></p>))}{v.global.map(n=><p key={n}><b>{n}</b><span>{injuryByName[n]?.[2]}</span></p>)}</div>
   {w.next!==0&&<button type="button" onClick={()=>act({type:'consume-stun'})}>Teste realizado · consumir Atordoado (−2d)</button>}
   {(c.rc===0||w.exhausted)&&c.hasKagune&&<p className="vats-warning">RC indisponível: regeneração ativa e técnicas de RC bloqueadas. Aplique “Exaurido de RC” se o corpo depende de RC para se manter.</p>}
  </section>
  <details className="vats-details" open><summary>Regeneração <span>{preview.total} PV recuperáveis · {preview.cost} RC</span></summary><div className="vats-detail-body"><div className="regen-line"><div><strong>{preview.amount} PV por região</strong><p>Somente PV efetivamente curados contam. Cada {preview.threshold} PV acumulados custa 2 RC; saldo atual: {v.meter} PV. Sobretaxa de condições: +{w.regenCost} RC.</p></div><button type="button" disabled={v.healedTurn===v.turn||!preview.total||c.rc<preview.cost||w.exhausted} onClick={()=>act({type:'passive'})}>{v.healedTurn===v.turn?'Aplicada neste turno':`Regenerar · ${preview.cost} RC`}</button></div><p className="vats-help">Membros destruídos precisam ser reconstruídos. Cura não remove ferimentos automaticamente. Estômago destruído: a mesa define a sobretaxa não quantificada na regra.</p><div className="vats-power-actions">
   {c.superior===4&&<button disabled={blocked||c.rc<6+w.regenCost} onClick={()=>act({type:'full'})}>Cura total · {6+w.regenCost} RC</button>}
   {power('axolote')&&<button disabled={blocked||c.rc<6||v.axolotlTurn===v.turn} onClick={()=>act({type:'axolotl'})}>Axolote · 6 RC</button>}
   {power('carne-recusa')&&<button disabled={blocked||c.rc<20||v.fleshUsed} onClick={()=>act({type:'flesh'})}>Carne que se Recusa · 20 RC</button>}
   {power('respirar-fundo')&&<button disabled={v.breathe>=2} onClick={()=>act({type:'breathe'})}>Respirar Fundo · {v.breathe}/2</button>}
   {power('segundo-folego')&&<button disabled={v.secondWind||!regions.some(([id])=>hp(id)<=c.maxLife/2)} onClick={()=>act({type:'second'})}>Segundo Fôlego</button>}
   {power('anjo-morte')&&<button disabled={v.angel>=4||v.fleshUntil>v.turn} onClick={()=>act({type:'angel'})}>Confirmar abate · +2 RC ({v.angel}/4)</button>}
   {power('fortaleza-carne')&&<button disabled={blocked||c.rc<5||v.fortressTurn===v.turn} onClick={()=>act({type:'fortress'})}>Fortaleza de Carne · 5 RC</button>}
  </div></div></details>
  {c.hasKagune&&<details className="vats-details"><summary>Kakuhou & kagune <span>{v.kakuhouUntil>v.turn?`bloqueada por ${v.kakuhouUntil-v.turn} turnos`:'ver integridade e recuperação'}</span></summary><div className="vats-detail-body"><div className="kakuhou-status"><p>{v.kakuhouUntil>v.turn?`Kakuhou destruído. Kagune indisponível até o turno ${v.kakuhouUntil}.`:'Kakuhou íntegro. Destruição causa vazamento de 1d6 RC e bloqueia a kagune por 2 turnos.'}</p><button disabled={v.kakuhouUntil>v.turn} onClick={()=>act({type:'kakuhou'})}>Destruir Kakuhou</button></div><label className="vats-check"><input type="checkbox" checked={enemy} onChange={e=>setEnemy(e.target.checked)}/>Destruição causada pelo inimigo</label><div className="kagune-parts">{Array.from({length:c.tails},(_,i)=>{const p=v.parts[i]||{damage:0,ready:0,sacrificedUntil:0};return <article key={i}><h3>Kagune {i+1} <span>{Math.max(0,c.durability-p.damage)} / {c.durability} PV</span></h3><p>{p.ready?`Quebrada · regeneração a partir de T${Math.max(p.ready,v.kakuhouUntil)}`:'Íntegra'}{p.sacrificedUntil?' · sacrificada':''}</p><div className="vats-power-actions"><button disabled={!!p.ready} onClick={()=>act({type:'part-damage',index:i,amount,enemy})}>Dano · {amount}</button><button disabled={!!p.ready} onClick={()=>act({type:'break',index:i,enemy})}>Quebrar</button><button disabled={!p.ready||v.turn<Math.max(p.ready,p.sacrificedUntil,v.kakuhouUntil)||blocked||c.rc<2} onClick={()=>act({type:'part-regen',index:i})}>Regenerar · 2 RC</button>{power('hidra-faminta')&&<button disabled={!p.ready||!!p.sacrificedUntil||v.hydraTurn===v.turn||blocked||c.rc<5||v.kakuhouUntil>v.turn} onClick={()=>act({type:'hydra',index:i})}>Hidra · 5 RC</button>}{power('canibalismo-celular')&&<button disabled={!!p.ready||v.sacrifices>=2} onClick={()=>act({type:'sacrifice',index:i})}>Sacrificar cauda</button>}</div></article>;})}</div><div className="vats-power-actions">{power('continua-crescendo')&&<button disabled={v.growth<5||v.kakuhouUntil>v.turn} onClick={()=>act({type:'growth'})}>Crescimento · {v.growth}/5</button>}{power('centopeia')&&<button disabled={v.centipedeUsed||c.centipedeAllowed===false} onClick={()=>act({type:'centipede'})}>Ativar Centopeia · 3 turnos</button>}</div></div></details>}
  <details className="vats-details"><summary>Registro de combate <span>{v.rcSpent} RC gastos em ações</span></summary><ol className="combat-log">{v.log.length?v.log.map((line,i)=><li key={i}>{line}</li>):<li>Nenhum evento registrado.</li>}</ol></details>
  <footer className="vats-footer"><span>Usos limitados são salvos por personagem.</span>{confirm?<div><span>{confirm==='rest'?'Registrar descanso?':'Iniciar nova sessão?'}</span><button onClick={()=>{act({type:confirm});setConfirm('');}}>Confirmar</button><button onClick={()=>setConfirm('')}>Cancelar</button></div>:<div><button onClick={()=>setConfirm('rest')}>Registrar descanso</button><button onClick={()=>setConfirm('session')}>Nova sessão</button></div>}</footer>
 </div>;
}

function ContextTest({state:v,config:c,selected}:{state:VatsState;config:VatsConfig;selected:RegionId}){
 const [attribute,setAttribute]=useState('forca'),[context,setContext]=useState('normal');
 const w=penalties(v),r=v.body[selected];let delta=w.next;let restriction='';
 if(context==='limb'){
  delta-=r.effects.includes('Braço Quebrado')?2:r.effects.includes('Braço Ferido')?1:0;
  if(r.destroyed||r.effects.some(e=>['Braço Destruído','Perna Destruída','Mão Destruída'].includes(e)))restriction='Região inutilizada: ação indisponível.';
 }
 if(context==='effort')delta+=w.effort;
 if(context==='vision'){delta+=w.vision;if(v.body.head.effects.includes('Cego'))restriction='Cego: a mesa define a penalidade de visão.';}
 if(context==='hearing'){delta+=w.hearing;if(v.body.head.effects.includes('Surdo'))restriction='Surdo: não percebe som normalmente.';}
 if(context==='mobility'){if(v.body.legL.effects.includes('Perna Ferida')||v.body.legR.effects.includes('Perna Ferida'))delta-=1;if(v.global.includes('Esmagado'))delta-=2;if(w.movement===0)restriction='Deslocamento impedido ou limitado a rastejar; consulte os efeitos.';}
 const test=adjustTest(c.tests?.[attribute]||'0d8>>5',delta);
 return <div className="context-test"><label>Teste de<select value={attribute} onChange={e=>setAttribute(e.target.value)}>{Object.entries({forca:'Força',vigor:'Vigor',precisao:'Precisão',agilidade:'Agilidade',raciocinio:'Raciocínio',percepcao:'Percepção',presenca:'Presença',controle:'Controle'}).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label>Contexto<select value={context} onChange={e=>setContext(e.target.value)}><option value="normal">Geral</option><option value="limb">Usando a região selecionada</option><option value="effort">Esforço físico</option><option value="vision">Visão / acerto visual</option><option value="hearing">Audição</option><option value="mobility">Mobilidade</option></select></label><div><span>COM PENALIDADES</span><code>{restriction?'Restrito':test}</code></div>{restriction&&<p>{restriction}</p>}</div>;
}
